#!/usr/bin/env bash
# Turn the numpy wasm build into something a STATIC interpreter can use:
#   wasm-sysroot/lib/libnumpy.a            all extension objects, one archive
#   wasm-sysroot/lib/numpy_inittab.inc     the PyImport_Inittab entries for them
#   wasm-sysroot/lib/python3.13/site-packages/numpy/   the Python half
#
# Meson built each extension as a SIDE_MODULE .so, which is useless here: this
# Blender links CPython statically and has no dynamic loader. The objects behind
# those .so files are perfectly good though, so we archive them and register the
# module init functions in CPython's inittab instead.
set -euo pipefail

ROOT="${ROOT:-$HOME/blender-wasm}"
source "$ROOT/scripts/dep_common.sh"

B="$BLD/numpy-wasm"
NATIVE="$DEPS/build/python-native/python"
export PYTHONPATH="$HOME/.local/lib/python3.13/site-packages"
SP="$SYSROOT/lib/python3.13/site-packages"

[ -d "$B" ] || { echo "no numpy build at $B; run build_numpy.sh first" >&2; exit 1; }

# --- 1. one archive of every extension object -------------------------------
# The objects meson produced are PIC, because it builds every extension as a
# shared module. Linking those into this non-PIC static executable fails with
#   relocation R_WASM_TABLE_INDEX_REL_SLEB is not supported against an
#   undefined symbol `DOUBLE_fmax_indexed`
# on every function address numpy takes. There is no meson switch for it, so
# the helper below replays each compile from compile_commands.json with -fPIC
# dropped -- same sources, same generated headers, same defines.
log "recompiling numpy objects without -fPIC"
STAGE="$BLD/numpy-nopic"
rm -rf "$STAGE"
"$NATIVE" "$ROOT/scripts/recompile_numpy_nopic.py" "$B" "$STAGE" "$NPROC"

rm -f "$SYSROOT/lib/libnumpy.a"
emar qc "$SYSROOT/lib/libnumpy.a" "$STAGE"/*.o
emranlib "$SYSROOT/lib/libnumpy.a" 2>/dev/null || emar s "$SYSROOT/lib/libnumpy.a"
log "libnumpy.a: $(stat -c%s "$SYSROOT/lib/libnumpy.a") bytes, $(ls "$STAGE"/*.o | wc -l) objects"

# --- 2. the inittab fragment -------------------------------------------------
# One line per extension module: full dotted name -> its PyInit function.
# Written into the Blender tree so bpy_interface.cc can #include it by a
# plain relative path, and so a build without numpy staged simply does not
# find it (see the __has_include guard there).
INC="$ROOT/blender/source/blender/python/intern/numpy_static_inittab.inc"
{
  echo "/* Generated by scripts/package_numpy.sh -- do not edit. */"
  echo "/* numpy $(cat "$B/../../src"/numpy-*/numpy/version.py 2>/dev/null | sed -n 's/^version = \"\(.*\)\"/\1/p' | head -1) extension modules, statically linked. */"
} > "$INC"

DECL=""
ENTRIES=""
while IFS= read -r so; do
  rel="${so#"$B"/}"                      # numpy/_core/_multiarray_umath.cpython-...so
  dir=$(dirname "$rel")                  # numpy/_core
  base=$(basename "$rel")
  mod="${base%%.cpython-*}"              # _multiarray_umath
  dotted="$(echo "$dir" | tr '/' '.').$mod"
  DECL="${DECL}extern \"C\" PyObject *PyInit_${mod}(void);
"
  ENTRIES="${ENTRIES}    {\"${dotted}\", PyInit_${mod}},
"
done < <(find "$B" -name "*.cpython-313-wasm32-emscripten.so" \
           ! -name "*_tests.cpython*" | sort)

{
  echo "$DECL"
  echo "static struct _inittab numpy_inittab[] = {"
  echo "$ENTRIES"
  echo "    {nullptr, nullptr},"
  echo "};"
} >> "$INC"
log "numpy_static_inittab.inc: $(grep -c '^    {"' "$INC") modules"

# --- 3. the Python half ------------------------------------------------------
log "installing numpy python sources"
rm -rf "$SP/numpy"
DEST=$(mktemp -d)
src=$(ls -d "$DEPS/src"/numpy-*/ | head -1)
"$NATIVE" "$src/vendored-meson/meson/meson.py" install -C "$B" --destdir "$DEST" >/dev/null 2>&1 || true

# meson installs under $DEST$SYSROOT/... ; find the numpy package it produced.
found=$(find "$DEST" -maxdepth 8 -type d -name numpy -path "*site-packages*" | head -1)
if [ -z "$found" ]; then
  found=$(find "$DEST" -maxdepth 8 -type d -name numpy | head -1)
fi
[ -n "$found" ] || { echo "meson install produced no numpy tree" >&2; exit 1; }

mkdir -p "$SP"
cp -r "$found" "$SP/numpy"
rm -rf "$DEST"

# The .so files must go: they are side modules nothing can load, and leaving
# them would let the import system find a broken candidate before the builtin.
find "$SP/numpy" -name "*.so" -delete
find "$SP/numpy" -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
# Tests are a third of the tree and cannot run here.
find "$SP/numpy" -type d -name tests -exec rm -rf {} + 2>/dev/null || true

log "site-packages/numpy: $(du -sh "$SP/numpy" | cut -f1), $(find "$SP/numpy" -name '*.py' | wc -l) modules"
log "done"
